import type { GrantRound, Proposal, ReviewResult, SimilarityFinding, CommitteeDecision } from "./types";
import { DEFAULT_WEIGHTS } from "./scoring";

export const mockRounds: GrantRound[] = [
  {
    round_id: "grant_round_001",
    title: "GenLayer Builder Grants Q3",
    ecosystem: "GenLayer",
    description:
      "Funding for intelligent-contract applications, AI consensus tooling, public goods, and developer infrastructure on GenLayer Studionet.",
    funding_pool: 100000,
    deadline: "2026-09-30",
    criteria_weights: DEFAULT_WEIGHTS,
    plagiarism_sensitivity: "HIGH",
    visibility: "public",
    status: "Reviewing",
    applicant_count: 5,
  },
  {
    round_id: "grant_round_002",
    title: "Public Goods Wave VI",
    ecosystem: "Optimism Collective",
    description: "Retroactive funding for public-goods infrastructure benefiting the broader ecosystem.",
    funding_pool: 250000,
    deadline: "2026-08-15",
    criteria_weights: DEFAULT_WEIGHTS,
    plagiarism_sensitivity: "MEDIUM",
    visibility: "public",
    status: "Open",
    applicant_count: 12,
  },
  {
    round_id: "grant_round_003",
    title: "DAO Tooling Accelerator",
    ecosystem: "Aragon",
    description: "Accelerator track for governance tooling, voting UX, and treasury infrastructure.",
    funding_pool: 60000,
    deadline: "2026-07-20",
    criteria_weights: DEFAULT_WEIGHTS,
    plagiarism_sensitivity: "MEDIUM",
    visibility: "public",
    status: "Finalised",
    applicant_count: 8,
  },
];

const baseProp = (overrides: Partial<Proposal>): Proposal => ({
  proposal_id: overrides.proposal_id!,
  round_id: overrides.round_id ?? "grant_round_001",
  project_name: overrides.project_name!,
  team_name: overrides.team_name ?? "Independent Team",
  wallet: overrides.wallet ?? "0x" + "ab".repeat(20),
  contact: overrides.contact ?? "team@example.xyz",
  summary: overrides.summary!,
  problem: overrides.problem ?? "",
  solution: overrides.solution ?? "",
  why_ecosystem: overrides.why_ecosystem ?? "",
  architecture: overrides.architecture ?? "",
  milestones: overrides.milestones ?? "",
  timeline: overrides.timeline ?? "12 weeks",
  budget: overrides.budget ?? 20000,
  team_background: overrides.team_background ?? "",
  prior_work: overrides.prior_work ?? "",
  links: overrides.links ?? "",
  disclosure: overrides.disclosure ?? "",
  honesty_confirmed: true,
  proposal_hash: overrides.proposal_hash ?? "0x" + Math.random().toString(16).slice(2, 18).padEnd(16, "0"),
  status: overrides.status ?? "AI_REVIEWED",
  submitted_at: overrides.submitted_at ?? "2026-06-01",
});

export const mockProposals: Proposal[] = [
  baseProp({
    proposal_id: "proposal_001",
    project_name: "ProofAid",
    team_name: "Atlas Labs",
    summary: "AI-reviewed public-goods funding proof system that verifies impact claims via on-chain attestations.",
    problem: "Public-goods funders cannot verify if grantees actually delivered the impact they claimed.",
    solution: "An attestation registry combined with GenLayer-judged evidence reviews.",
    architecture: "Solidity attestation registry, GenLayer judge contract, indexer, dashboard.",
    milestones: "M1 registry, M2 judge contract, M3 dashboard, M4 audit",
    budget: 28000,
    status: "AI_REVIEWED",
  }),
  baseProp({
    proposal_id: "proposal_002",
    project_name: "DeFiSentinel",
    team_name: "Sentinel Research",
    summary: "Risk-monitoring agent for on-chain lending markets that flags emerging insolvency conditions.",
    problem: "Lending protocols lack early-warning systems for cascading liquidations.",
    solution: "Real-time risk model with GenLayer consensus on qualitative market-state assessments.",
    architecture: "Indexer, risk engine, GenLayer judgement contract, alerting frontend.",
    milestones: "M1 indexer, M2 risk model, M3 GenLayer integration, M4 launch",
    budget: 35000,
    status: "AI_REVIEWED",
  }),
  baseProp({
    proposal_id: "proposal_003",
    project_name: "CreatorCourt",
    team_name: "Court Collective",
    summary: "AI consensus originality court that adjudicates creator IP disputes using GenLayer judgement.",
    problem: "Creators have no fast, fair forum to resolve originality disputes.",
    solution: "Dispute filing flow with GenLayer-judged originality findings.",
    architecture: "Filing contract, evidence storage, GenLayer judge, public dossier viewer.",
    milestones: "M1 filing flow, M2 judge prompt, M3 dossier viewer",
    budget: 22000,
    status: "AI_REVIEWED",
  }),
  baseProp({
    proposal_id: "proposal_004",
    project_name: "GrantBot Lite",
    team_name: "Solo Builder",
    summary: "An AI grant bot that uses AI to do AI things with grants and blockchain synergy.",
    problem: "Grants are hard.",
    solution: "Use AI to make grants easier with AI.",
    architecture: "AI + blockchain.",
    milestones: "Build it, ship it.",
    budget: 40000,
    status: "AI_REVIEWED",
  }),
  baseProp({
    proposal_id: "proposal_005",
    project_name: "CopyFund",
    team_name: "FundCopy Labs",
    summary: "AI consensus originality court that adjudicates creator IP disputes using AI judgement on chain.",
    problem: "Creators have no fast, fair forum to resolve originality disputes.",
    solution: "Dispute filing flow with AI-judged originality findings on chain.",
    architecture: "Filing contract, evidence storage, AI judge, public dossier viewer.",
    milestones: "M1 filing flow, M2 judge prompt, M3 dossier viewer",
    budget: 24000,
    status: "MANUAL_REVIEW_REQUIRED",
  }),
];

export const mockReviews: Record<string, ReviewResult> = {
  proposal_001: {
    proposal_id: "proposal_001",
    overall_score: 87,
    originality_score: 85,
    technical_feasibility_score: 88,
    ecosystem_alignment_score: 92,
    team_capability_score: 84,
    impact_score: 86,
    budget_reasonableness_score: 80,
    plagiarism_risk: "LOW",
    similarity_risk: "LOW",
    delivery_risk: "LOW",
    strengths: [
      "Clear problem-solution fit grounded in real funder pain.",
      "Architecture leverages GenLayer for the part that benefits from non-determinism.",
      "Milestones are concrete and individually verifiable.",
    ],
    weaknesses: [
      "Team's prior attestation work is referenced but not linked.",
      "Cost split across milestones not itemised.",
    ],
    red_flags: [],
    reviewer_questions: [
      "Which attestation standards (EAS, custom) will the registry conform to?",
      "What is the fallback if the judge contract disagrees with off-chain evidence?",
    ],
    recommended_decision: "ACCEPT",
    summary: "Strong, focused proposal with a well-scoped GenLayer use case and credible delivery plan.",
    ranking_rationale: "Highest overall feasibility-adjusted score; minimal risk across all axes.",
  },
  proposal_002: {
    proposal_id: "proposal_002",
    overall_score: 81,
    originality_score: 76,
    technical_feasibility_score: 84,
    ecosystem_alignment_score: 78,
    team_capability_score: 85,
    impact_score: 82,
    budget_reasonableness_score: 78,
    plagiarism_risk: "LOW",
    similarity_risk: "LOW",
    delivery_risk: "MEDIUM",
    strengths: [
      "Experienced research team with verifiable prior work.",
      "Risk model is technically sound and well-cited.",
    ],
    weaknesses: [
      "GenLayer integration is bolted on rather than central to the design.",
      "Timeline for production launch may be optimistic.",
    ],
    red_flags: [],
    reviewer_questions: [
      "Could the risk model run without GenLayer? If so, what does GenLayer actually contribute?",
    ],
    recommended_decision: "ACCEPT",
    summary: "Solid proposal but GenLayer's role needs sharpening.",
    ranking_rationale: "Strong execution credibility; minor deduction for medium delivery risk.",
  },
  proposal_003: {
    proposal_id: "proposal_003",
    overall_score: 78,
    originality_score: 82,
    technical_feasibility_score: 74,
    ecosystem_alignment_score: 80,
    team_capability_score: 70,
    impact_score: 80,
    budget_reasonableness_score: 78,
    plagiarism_risk: "MEDIUM",
    similarity_risk: "HIGH",
    delivery_risk: "MEDIUM",
    strengths: [
      "Original framing of originality adjudication as a court process.",
      "Good alignment with GenLayer's strengths in qualitative judgement.",
    ],
    weaknesses: [
      "Substantial overlap with another submission in this round (CopyFund).",
      "Team capability is light for a court-style adjudication system.",
    ],
    red_flags: ["High similarity overlap with proposal_005."],
    reviewer_questions: [
      "Can the team explain the relationship, if any, with CopyFund?",
    ],
    recommended_decision: "WAITLIST",
    summary: "Compelling idea overshadowed by a serious similarity overlap that needs clarification.",
    ranking_rationale: "Strong score adjusted down by similarity risk; pending clarification.",
  },
  proposal_004: {
    proposal_id: "proposal_004",
    overall_score: 32,
    originality_score: 28,
    technical_feasibility_score: 30,
    ecosystem_alignment_score: 40,
    team_capability_score: 35,
    impact_score: 30,
    budget_reasonableness_score: 25,
    plagiarism_risk: "LOW",
    similarity_risk: "LOW",
    delivery_risk: "HIGH",
    strengths: ["Submitted on time."],
    weaknesses: [
      "Buzzword-heavy with no concrete technical detail.",
      "Budget of $40k is unjustified relative to scope.",
      "No team background or prior work disclosed.",
    ],
    red_flags: ["Vague AI claims without implementation detail.", "Inflated budget."],
    reviewer_questions: ["What does the system actually build and ship?"],
    recommended_decision: "REJECT",
    summary: "Lacks the substance required for serious consideration.",
    ranking_rationale: "Low across all axes; high delivery risk.",
  },
  proposal_005: {
    proposal_id: "proposal_005",
    overall_score: 71,
    originality_score: 35,
    technical_feasibility_score: 72,
    ecosystem_alignment_score: 78,
    team_capability_score: 75,
    impact_score: 76,
    budget_reasonableness_score: 80,
    plagiarism_risk: "HIGH",
    similarity_risk: "CRITICAL",
    delivery_risk: "MEDIUM",
    strengths: ["Architecturally coherent."],
    weaknesses: [
      "Near-duplicate of CreatorCourt with cosmetic rewording.",
      "Originality claims are not credible given the overlap.",
    ],
    red_flags: ["Critical similarity overlap with proposal_003 — likely derivative."],
    reviewer_questions: [
      "Disclose any relationship with the CreatorCourt team.",
      "Identify any sections authored independently.",
    ],
    recommended_decision: "FLAG_FOR_MANUAL_REVIEW",
    summary: "Critical similarity overlap requires human review before any decision.",
    ranking_rationale: "High raw score reduced sharply by critical similarity risk.",
  },
};

export const mockSimilarities: Record<string, SimilarityFinding> = {
  proposal_005: {
    similarity_level: "CRITICAL",
    similarity_score: 92,
    matched_sections: [
      "Problem statement (verbatim phrasing across 3 sentences).",
      "Solution overview (AI/GenLayer swap is the only differentiator).",
      "Architecture bullets (1:1 ordering with renamed terms).",
    ],
    reasoning_summary:
      "CopyFund's proposal mirrors CreatorCourt's structure and language at a level inconsistent with independent authorship.",
    recommended_action: "POSSIBLE_DISQUALIFICATION",
    compared_against: "proposal_003",
  },
  proposal_003: {
    similarity_level: "HIGH",
    similarity_score: 84,
    matched_sections: ["Mirror sections in proposal_005 — see CopyFund finding."],
    reasoning_summary: "Counterpart of the CopyFund finding; CreatorCourt appears to be the earlier submission.",
    recommended_action: "MANUAL_REVIEW",
    compared_against: "proposal_005",
  },
};

export const mockDecisions: Record<string, CommitteeDecision> = {};
